Milestone 5
Azeem838/calculator-app pull request #5
Opened 2020-09-24 11:14 UTC by Azeem838

In this milestone, the following were implemented in App.js

1. the state was introduced in App.js;
2. handleClick; and 
3. render methods in App.js;
4. handleClick in Button.js
5. handleClick in ButtonPanel.js

Please find my commits below,
Thank you.

2020-09-24 20:11 UTC, Forison requested changes
## Status:: Change required❌

# 🙋‍♂️ Azeem  

### You have done a good job so far, the project looks good but there are a few computations issues we have to address🤗.
* [x] The image in the readme is not showing, kindly address this issue.
* [ ] When it comes to ```%``` it works well on only one operand. ie.  8%===0.08 which is good but when we have ie `(8-5)%` it returns `7.6` which is not right. Let address this flaw. When a user selects 8 then, - then `5` then `%` the result should `0.03`.
The point here is that, when `next`, `operation` and `total` are occupied and the subsequent selections is an operand the current value of `next`, `operation` and `total` must be computed and the new operand should be the new operator value. 

* [ ] Your application should allow continuous computation.
 ie `10-7+3+2` would be handled like below.
`10-7` => the next operand is + upon selecting should trigger a computation and return 3 + then
`3+3`=> next operand is + then upon selecting it should trigger a computation and return 6 + then 
and so on.
> In summary when next, operator and total are occupied and the subsequent selection is an operand, resolve them and store the result in total, let the newly selected operand occupy the operator and then continue

**[OPTIONAL]**

* [x] I think making the currently selected operand visible make the UI more user friendly

### That is it kindly make the change and submit the project for a re-review👨‍🎨.
#### Happy coding👨‍💻 
Addo Forison

2020-09-25 07:58 UTC, Azeem838 commented
Hi,

The percentage operation works as follows: 
When a user selects "8' then, "-" then 5 then "%" the result should 7.6 and not 0.03. Following BODMAS rule, the "8" is pressed and then "-" and then the "5" and then "%" so the mathematical calculation looks as follows:
8-5% = 7.6
which can be said as eight minus 5 percent and not:
(8-5)% = 0.03
If the desired result is 0.03, brackets will need to be added to the calculator and then the logic will need to be updated to include BODMAS rules.

However, if a user enters "8" then "-" then "5" and then presses "=", the result will be 3, after which the user can press "%" which will turn the result into a percentage which in this case is 0.03. This functionality has been updated in the calculator.

Thank you.

2020-09-25 16:41 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @Azeem838 good job working on this you have done really well to get it to this point please I did a recording to point out some of the errors I noticed, please check it out [here](https://www.loom.com/share/dd3a520fa43744649eb88d712989b526)

**Please make changes and request for another review** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-25 18:09 UTC, suretrust requested changes
Hi @Azeem838, 👋 

### Great job squashing those bugs! 🙌 Just one more thing. 👇 

- [ ] Let's fix the result such that it stays within the `Display` container, from the screenshot below, see it overflowing.

<img width="751" alt="Screenshot 2020-09-25 at 19 07 48" src="https://user-images.githubusercontent.com/31304943/94301420-70a59880-ff62-11ea-9237-8cb8298dfc97.png">


**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-09-26 21:35 UTC, shloch approved these changes
## Hello @Azeem838 

Great job with addressing the issues raised above...keep up with the good work
![calc](https://user-images.githubusercontent.com/40712459/94350685-960cd200-0048-11eb-8217-40af91aa86af.gif)

I tested them and see that you nailed the points.
Take note of the ONE comment below though.

Happy coding

2020-09-26 21:35 UTC, shloch commented on src/logic/operate.js
>        break;
in case of this error (division by zero error), you can write `NaN` on screen instead of `'0'` as you did
(Please do this before you merge)

2020-09-28 06:21 UTC, merged